package com.implantiq;

import android.content.Intent;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Paint;
import android.graphics.pdf.PdfDocument;
import android.net.Uri;
import android.os.Bundle;
import android.widget.TextView;
import android.widget.Toast;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.content.FileProvider;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Locale;

public class ResultActivity extends AppCompatActivity {

    private String patientName, grade, patientId;
    private double survivalYears, successRate;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_result);

        survivalYears = getIntent().getDoubleExtra("survival_years", 11.4);
        successRate = getIntent().getDoubleExtra("success_rate", 92.0);
        grade = getIntent().getStringExtra("grade");
        if (grade == null) grade = "Excellent";
        patientName = getIntent().getStringExtra("patient_name");
        if (patientName == null) patientName = "Dayakar";
        patientId = getIntent().getStringExtra("patient_id");
        if (patientId == null) patientId = "PID-2026";

        ((TextView) findViewById(R.id.tv_patient_name_result)).setText(patientName);
        ((TextView) findViewById(R.id.tv_survival_val)).setText(String.format(Locale.US, "%.1f Years", survivalYears));
        ((TextView) findViewById(R.id.tv_success_rate_val)).setText(String.format(Locale.US, "%.0f%%", successRate));
        ((TextView) findViewById(R.id.tv_grade_val)).setText(grade);
        ((TextView) findViewById(R.id.tv_patient_id_label)).setText("ID: #" + patientId);

        findViewById(R.id.btn_back).setOnClickListener(v -> finish());
        
        findViewById(R.id.btn_pdf).setOnClickListener(v -> generateAndSharePDF());
        findViewById(R.id.btn_csv).setOnClickListener(v -> generateAndShareCSV());
        findViewById(R.id.btn_share).setOnClickListener(v -> shareViaEmail());

        findViewById(R.id.btnNewPrediction).setOnClickListener(v -> {
            startActivity(new Intent(this, PredictActivity.class));
            finish();
        });
    }

    private void generateAndSharePDF() {
        PdfDocument document = new PdfDocument();
        PdfDocument.PageInfo pageInfo = new PdfDocument.PageInfo.Builder(300, 600, 1).create();
        PdfDocument.Page page = document.startPage(pageInfo);

        Canvas canvas = page.getCanvas();
        Paint paint = new Paint();
        paint.setColor(Color.BLACK);
        paint.setTextSize(14);

        int y = 50;
        canvas.drawText("IMPLANT IQ - CLINICAL REPORT", 50, y, paint);
        y += 40;
        paint.setTextSize(12);
        canvas.drawText("Patient ID: " + patientId, 50, y, paint);
        y += 20;
        canvas.drawText("Patient Name: " + patientName, 50, y, paint);
        y += 40;
        canvas.drawText("Survival Prediction: " + survivalYears + " Years", 50, y, paint);
        y += 20;
        canvas.drawText("Success Probability: " + successRate + "%", 50, y, paint);
        y += 20;
        canvas.drawText("Clinical Grade: " + grade, 50, y, paint);
        y += 60;
        paint.setTextSize(10);
        canvas.drawText("Generated by ImplantIQ AI System", 50, y, paint);

        document.finishPage(page);

        File file = new File(getExternalCacheDir(), "Clinical_Report_" + patientId + ".pdf");
        try {
            document.writeTo(new FileOutputStream(file));
            shareFile(file, "application/pdf");
        } catch (IOException e) {
            Toast.makeText(this, "PDF Generation Failed", Toast.LENGTH_SHORT).show();
        }
        document.close();
    }

    private void generateAndShareCSV() {
        StringBuilder csvData = new StringBuilder();
        csvData.append("PatientID,Name,SurvivalYears,SuccessRate,Grade\n");
        csvData.append(patientId).append(",")
               .append(patientName).append(",")
               .append(survivalYears).append(",")
               .append(successRate).append(",")
               .append(grade).append("\n");

        File file = new File(getExternalCacheDir(), "Analysis_Data_" + patientId + ".csv");
        try {
            FileOutputStream out = new FileOutputStream(file);
            out.write(csvData.toString().getBytes());
            out.close();
            shareFile(file, "text/csv");
        } catch (IOException e) {
            Toast.makeText(this, "CSV Export Failed", Toast.LENGTH_SHORT).show();
        }
    }

    private void shareViaEmail() {
        String body = "Clinical Prediction Report\n\n" +
                      "Patient Name: " + patientName + "\n" +
                      "Predicted Survival: " + survivalYears + " years\n" +
                      "Success Rate: " + successRate + "%\n" +
                      "Grade: " + grade;
        
        Intent intent = new Intent(Intent.ACTION_SEND);
        intent.setType("text/plain");
        intent.putExtra(Intent.EXTRA_SUBJECT, "Clinical Analysis: " + patientName);
        intent.putExtra(Intent.EXTRA_TEXT, body);
        startActivity(Intent.createChooser(intent, "Share Report via..."));
    }

    private void shareFile(File file, String mimeType) {
        Uri uri = FileProvider.getUriForFile(this, getPackageName() + ".provider", file);
        Intent intent = new Intent(Intent.ACTION_SEND);
        intent.setType(mimeType);
        intent.putExtra(Intent.EXTRA_STREAM, uri);
        intent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);
        startActivity(Intent.createChooser(intent, "Share Clinical File"));
    }
}
